# --- CONFIGURAÇÃO MAILTRAP (Copie do seu painel) ---
spring.mail.username=7dec00a39c8e75
spring.mail.password=893033d13e6829

# No Mailtrap, o remetente pode ser qualquer um para testes
app.mail.from=noreply@mind.com
